sudo: false
language: python
python:
 - "2.7"
branches:
  except:
    # skip version tags
    /^\d+\.\d+(\.\d+)$/
install:
 - pip install pycodestyle pydocstyle nose coverage pylint --upgrade
 - "pip install --only-binary :all: numpy --upgrade"
script:
 - python setup.py nosetests
 - pycodestyle derivcheck.py basic_example.py setup.py
 - pycodestyle --ignore=E731 test_derivcheck.py
 - pydocstyle setup.py derivcheck.py test_derivcheck.py basic_example.py
 - pylint derivcheck.py test_derivcheck.py basic_example.py
