sudo: false
# Do not use Travis Python to save some time.
language: generic
env:
  - MYCONDAPY=2.7
  - MYCONDAPY=3.6
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$MYCONDAPY" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  # Useful for debugging any issues with conda
  - conda info -a

  # Build package
  - DERIVCHECK_VERSION=$(pythin -c "import setup; print setup.get_version()")
  - echo "{% set version = "${DERIVCHECK_VERSION}"  %}" > conda/meta.yaml
  - cat conda/meta.yaml.template >> conda/meta.yaml
  - conda build conda

  # Install dependencies in conda test environment
  - conda install create -q -n test-environment python=$MYCONDAPY pycodestyle nose coverage pylint future numpy anaconda-client
  - source activate test-environment
  - pip install pydocstyle

  # Packaging
  - python setup.py sdist

  # Installation
  - conda install --use-local derivcheck
script:
  # Test outside source tree, to make sure we test the installed version.
  - (cd; nosetests derivcheck)
  # Code quality tests...
  - pycodestyle derivcheck.py basic_example.py setup.py
  - pycodestyle --ignore=E731 test_derivcheck.py
  - pydocstyle setup.py derivcheck.py test_derivcheck.py basic_example.py
  - pylint derivcheck.py test_derivcheck.py basic_example.py
deploy:
  # two different release mechanisms, one for stable and one for pre releases.
  - provider: releases
    api_key:
      secure: T+bNTJYuqx5rJTNH890E1AcQ2j1VGsV9klcc186TdblnyZgxkQFSJFLMkc8glhc4wjUsPhMjrA2vwLlfepHoU8CvrhyjXrosz/Gr5ETUdxCGBAPCtyKm7SnMYoYtJs9R53WqEAzLDS4TNJD/NvF+Gw5+6itn+PrGk115+HeVRMhL4A7F2GKTM1gTmpqsfxbbpmtQvpQMhdoV5O4ASqZWotdqytOV1YWVb+fI8S20A/XnkxdcjkgINaWBsxfHBMWobYKdDJcYXUxeO5FBIoLSOUiC1elp/8DCowT2BZSX+Zb4ETvGJs6ryyvYxSO90qg260Uc4j5NmMaTkRn3694D/bX4i7ZDzziY+2rK8zjIjswfUuDEcbdPPKnp/P9sFXOb90BSOxTwcYzJzJt46WDrvrWFa9Y+F2MT60fE9LZZ23TkEFAKYhC6FGbFZEGvBRdr8YgGvCgpAnwv3oJZk+8V648at/hYOTvL5mRY+R5cMr4lkf/Hw3hgrhB8BZ8DCWBD3fQNIkD9qrAJuJjOG5R44G4QAnA2EW8kzucDv/sjoRpx28Bbklpg97QgqTVL0GcEVYt6DnqHIHTYtKysnRSbDyXX8uX9z6R0TkdQOYsJhNI+3a046uU/Bd05MauwvEdDWcsUO2jnRHqj/8zpmxeyc8ND8b+3gInd3Ae+TQQ9yxE=
    file: dist/derivcheck-${TRAVIS_TAG}.tar.gz
    on:
      repo: tovrstra/derivcheck
      tags: true
      condition: '$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7'
    prerelease: false
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: T+bNTJYuqx5rJTNH890E1AcQ2j1VGsV9klcc186TdblnyZgxkQFSJFLMkc8glhc4wjUsPhMjrA2vwLlfepHoU8CvrhyjXrosz/Gr5ETUdxCGBAPCtyKm7SnMYoYtJs9R53WqEAzLDS4TNJD/NvF+Gw5+6itn+PrGk115+HeVRMhL4A7F2GKTM1gTmpqsfxbbpmtQvpQMhdoV5O4ASqZWotdqytOV1YWVb+fI8S20A/XnkxdcjkgINaWBsxfHBMWobYKdDJcYXUxeO5FBIoLSOUiC1elp/8DCowT2BZSX+Zb4ETvGJs6ryyvYxSO90qg260Uc4j5NmMaTkRn3694D/bX4i7ZDzziY+2rK8zjIjswfUuDEcbdPPKnp/P9sFXOb90BSOxTwcYzJzJt46WDrvrWFa9Y+F2MT60fE9LZZ23TkEFAKYhC6FGbFZEGvBRdr8YgGvCgpAnwv3oJZk+8V648at/hYOTvL5mRY+R5cMr4lkf/Hw3hgrhB8BZ8DCWBD3fQNIkD9qrAJuJjOG5R44G4QAnA2EW8kzucDv/sjoRpx28Bbklpg97QgqTVL0GcEVYt6DnqHIHTYtKysnRSbDyXX8uX9z6R0TkdQOYsJhNI+3a046uU/Bd05MauwvEdDWcsUO2jnRHqj/8zpmxeyc8ND8b+3gInd3Ae+TQQ9yxE=
    file: dist/derivcheck-${TRAVIS_TAG}.tar.gz
    on:
      repo: tovrstra/derivcheck
      tags: true
      condition: '$TRAVIS_TAG == *[ab]* && $MYCONDAPY == 2.7'
    prerelease: true
    skip_cleanup: true
