sudo: false
language: python
python:
 - "2.7"
branches:
  except:
    # skip version tags
    /^\d+\.\d+(\.\d+)$/
install:
 - pip install pycodestyle
script:
 - python setup.py nosetests --processes=2 --process-timeout=100
 - pycodestyle derivcheck.py
 - pycodestyle --ignore=E731 test_derivcheck.py
 - pycodestyle basic_example.py
