package:
  version: "{{ load_setup_py_data().version }}"
  name: 'derivcheck'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  run:
    - python
    - numpy
    - nose
  build:
    - python
    - setuptools

about:
  dev_url: https://github.com/tovrstra/derivcheck
  description: A robust and very sensitive tester for analytic partial derivatives
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  summary: A robust and very sensitive tester for analytic partial derivatives
  home: https://github.com/tovrstra/derivcheck
  license_file: LICENSE.txt
  doc_url: https://github.com/tovrstra/derivcheck

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
