package:
  version: "{{ PROJECT_VERSION }}"
  name: 'derivcheck'

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy

test:
  requires:
    - python
    - numpy
    - pytest
    - pytest-xdist
  imports:
    - derivcheck
  commands:
    - pytest -v --pyargs derivcheck -n auto

about:
  dev_url: https://github.com/theochem/derivcheck
  description: A robust and very sensitive tester for analytic partial derivatives
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  summary: A robust and very sensitive tester for analytic partial derivatives
  home: https://github.com/theochem/derivcheck
  license_file: LICENSE.txt
  doc_url: https://github.com/theochem/derivcheck

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
